
from random import randint


op=str(input("m-Manual\na-Automatico\ns-Salir:     "))
while(op!='s'):
    if(op=='m'):
        c=open('machina.txt','a+')
        c.write("\n\nMODO MANUAL: ")
        cad1=[]
        cad3=""
        estado=0
        boo=True
        CAD=str(input("Introduzca la cadena: "))
        for i in CAD:
            cad3=cad3+i
            cad1.append(i)
        c.write(cad3+"\n")
        if(cad1==[]):
            print("La maquina no lo acepta")
            c.write("La maquina no lo acepta")
        else:    
            print("q"+str(estado))
            c.write("q"+str(estado)+"-|")
            print(cad1)
        j=0#lleva el indice
        while(boo!=False):
            if(estado==0):
                if(cad1[j]=='0'):
                    cad1[j]='x'
                    estado=1
                    if(j==len(cad1)-1):
                        print("(q"+str(estado)+",x,R)")
                        c.write("(q"+str(estado)+",x,R)")
                        print(cad1)
                        print("Truena\n")
                        c.write("\nTruena\n")
                        boo=False
                    else:
                        j=j+1
                        print("(q"+str(estado)+",x,R)")
                        c.write("(q"+str(estado)+",x,R)->")
                        print(cad1)
                elif(cad1[j]=='y'):
                    estado=3
                    if(j==len(cad1)-1):
                        print("(q"+str(estado)+",y,R)")
                        c.write("(q"+str(estado)+",y,R)->")
                        print(cad1)
                else:
                    print("truena\n")
                    c.write("\ntruena\n")
                    boo=False
            elif(estado==1):
                if(cad1[j]=='0'):
                    #estado=1
                    if(j==len(cad1)-1):
                        print("(q"+str(estado)+",0,R)")
                        c.write("(q"+str(estado)+",0,R)")
                        print(cad1)
                        print("Truena\n")
                        c.write("\nTruena\n")
                        boo=False
                    else:
                        j=j+1
                        print("(q"+str(estado)+",0,R)")
                        c.write("(q"+str(estado)+",0,R)->")
                        print(cad1)
                elif(cad1[j]=='1'):
                    cad1[j]='y'
                    estado=2
                    j=j-1
                    print("(q"+str(estado)+",y,L)")
                    c.write("(q"+str(estado)+",y,L)->")
                    print(cad1)
                elif(cad1[j]=='y'):
                    #estado=1
                    if(j==len(cad1)-1):
                        print("(q"+str(estado)+",y,R)")
                        c.write("(q"+str(estado)+",y,R)")
                        print(cad1)
                        print("Truena\n")
                        c.write("\nTruena\n")
                        boo=False
                    else:
                        j=j+1
                        print("(q"+str(estado)+",y,R)")
                        c.write("(q"+str(estado)+",y,R)->")
                        print(cad1)
                else:
                    print("truena\n")
                    c.write("\ntruena\n")
                    boo=False
            elif(estado==2):
                if(cad1[j]=='0'):
                    #estado=2
                    j=j-1
                    print("(q"+str(estado)+",0,L)")
                    c.write("(q"+str(estado)+",0,L)->")
                    print(cad1)
                elif(cad1[j]=='x'):
                    estado=0
                    j=j+1
                    print("(q"+str(estado)+",x,R)")
                    c.write("(q"+str(estado)+",x,R)->")
                    print(cad1)
                elif(cad1[j]=='y'):
                    estado=2
                    j=j-1
                    print("(q"+str(estado)+",y,L)")
                    c.write("(q"+str(estado)+",y,L)->")
                    print(cad1)
                else:
                    print("truena\n")
                    c.write("\ntruena\n")
                    boo=False
            elif(estado==3):
                if(cad1[j]=='y'):
                    if(j==len(cad1)-1):
                        if((('0' in cad1) or ('1' in cad1))!=False):#si hay un 1 o un 0
                            print("Truena\n")
                            c.write("\nTruena\n")
                            boo=False
                        else:
                            estado=4
                            print("(q"+str(estado)+",B,R)")
                            c.write("(q"+str(estado)+",B,R)")
                            print(cad1)
                            print("SIRVE\n")
                            c.write("\nSIRVE\n")
                            boo=False
                    else:
                        j=j+1
                        print("(q"+str(estado)+",y,R)")
                        c.write("(q"+str(estado)+",y,R)->")
                        print(cad1)
                else:
                    #si recibe cualquier cosa que no sea y o B
                    print("Truena\n")
                    c.write("\ntruena\n")
                    boo=False
        c.close()
        op=str(input("m-Manual\na-Automatico\ns-Salir:     "))
    elif(op=='a'):########################################################################
        random1=randint(0,3)
        cad2=[]
        cad3=""#quiero que se vea en la lista y no puedo mandar listas...
        boo=True
        j=0
        estado=0
        for i in range(0,random1):
            b=randint(0,1)
            cad3=cad3+str(b)
            cad2.append(str(b))
        #print("\n"+str(random1))
        f=open('machina.txt','a+')
        f.write("\n\nMODO AUTOMATICO: ")
        if(cad2==[]):
            print("vacio... La maquina no lo acepta")
            f.write("\nvacio... La maquina no lo acepta")
        else:    
            print("q"+str(estado))
            print(cad2)
            f.write(cad3+"\n")
            f.write("q"+str(estado)+"->")
        while(boo!=False):
            if(estado==0):
                if(cad2[j]=='0'):
                    cad2[j]='x'
                    estado=1
                    if(j==len(cad2)-1):
                        print("(q"+str(estado)+",x,R)")
                        print(cad2)
                        print("Truena\n")
                        f.write("(q"+str(estado)+",x,R)")
                        f.write("\nTruena\n")
                        boo=False
                    else:
                        j=j+1
                        print("(q"+str(estado)+",x,R)")
                        f.write("(q"+str(estado)+",x,R)->")
                        print(cad2)
                elif(cad2[j]=='y'):
                    estado=3
                    if(j==len(cad2)-1):
                        print("(q"+str(estado)+",y,R)")
                        f.write("(q"+str(estado)+",y,R)->")
                        print(cad2)
                else:
                    print("truena\n")
                    f.write("truena\n")
                    boo=False
            elif(estado==1):
                if(cad2[j]=='0'):
                    #estado=1
                    if(j==len(cad2)-1):
                        print("(q"+str(estado)+",0,R)")
                        print(cad2)
                        print("Truena\n")
                        f.write("(q"+str(estado)+",0,R)")
                        f.write("\nTruena\n")
                        boo=False
                    else:
                        j=j+1
                        print("(q"+str(estado)+",0,R)")
                        f.write("(q"+str(estado)+",0,R)->")
                        print(cad2)
                elif(cad2[j]=='1'):
                    cad2[j]='y'
                    estado=2
                    j=j-1
                    print("(q"+str(estado)+",y,L)")
                    f.write("(q"+str(estado)+",y,L)->")
                    print(cad2)
                elif(cad2[j]=='y'):
                    #estado=1
                    if(j==len(cad2)-1):
                        print("(q"+str(estado)+",y,R)")
                        f.write("(q"+str(estado)+",y,R)")
                        print(cad2)
                        print("Truena\n")
                        f.write("\nTruena\n")
                        boo=False
                    else:
                        j=j+1
                        print("(q"+str(estado)+",y,R)")
                        f.write("(q"+str(estado)+",y,R)->")
                        print(cad2)
                else:
                    print("truena\n")
                    f.write("\ntruena\n")
                    boo=False
            elif(estado==2):
                if(cad2[j]=='0'):
                    #estado=2
                    j=j-1
                    print("(q"+str(estado)+",0,L)")
                    f.write("(q"+str(estado)+",0,L)->")
                    print(cad2)
                elif(cad2[j]=='x'):
                    estado=0
                    j=j+1
                    print("(q"+str(estado)+",x,R)")
                    f.write("(q"+str(estado)+",x,R)->")
                    print(cad2)
                elif(cad2[j]=='y'):
                    estado=2
                    j=j-1
                    print("(q"+str(estado)+",y,L)")
                    f.write("(q"+str(estado)+",y,L)->")
                    print(cad2)
                else:
                    print("truena\n")
                    f.write("\ntruena\n")
                    boo=False
            elif(estado==3):
                if(cad2[j]=='y'):
                    if(j==len(cad2)-1):
                        if((('0' in cad2) or ('1' in cad2))!=False):#si hay un 1 o un 0
                            print("Truena\n")
                            f.write("\ntruena\n")
                            boo=False
                        else:
                            estado=4
                            print("(q"+str(estado)+",B,R)")
                            f.write("(q"+str(estado)+",B,R)")
                            print(cad2)
                            print("SIRVE\n")
                            f.write("\nSIRVE\n")
                            boo=False
                    else:
                        j=j+1
                        print("(q"+str(estado)+",y,R)")
                        f.write("(q"+str(estado)+",y,R)->")
                        print(cad2)
                else:
                    #si recibe cualquier cosa que no sea y o B
                    print("Truena\n")
                    f.write("\ntruena\n")
                    boo=False

        f.close()

        op=str(input("m-Manual\na-Automatico\ns-Salir:     "))
    else:
        op=str(input("m-Manual\na-Automatico\ns-Salir:     "))
